export { default } from './InputPlaceHolder'
export { default as InputAbove } from './InputAbove'
export { default as InputPlaceHolder } from './InputPlaceHolder'
export { default as InputInLine } from './InputInLine'
export { default as InputTag } from './InputTag'
export { default as InputNumber } from './InputNumber'
