export { default as DashBoard } from './DashBoard'
export { default as User } from './User'
export { default as Products } from './Products'
export { default as Revenue } from './Revenue'
export { default as Accounts } from './Accounts'
export { default as Stores } from './Stores'
export { default as Categories } from './Categories'
export { default as Customers } from './Customers'
